Process for prepping a SafeGraph zip file:

In [68]:
import pandas as pd
import datetime as dt
import timedelta

In [69]:
date_string_format = '%Y/%m/%d %H:%M:%S %p'
date_parserer = lambda s: pd.to_datetime(s,date_string_format)

path = r'C:\Users\nelms\Documents\Penn\MUSA-508\MUSA508_FINAL_SFPARK\SFMTA_Parking_Meter_Detailed_Revenue_Transactions.csv'
park19 = pd.read_csv(
    path, 
    parse_dates=[4,5],
    #date_parser=date_parsererff
    infer_datetime_format=True,
    dayfirst=False,
    cache_dates=True
    )

#cols = [col for col in list(park19) if col not in ['PAYMENT_TYPE', 'METER_EVENT_TYPE']]
#park19 = park19[cols]

,TRANSMISSION_DATETIME,POST_ID,STREET_BLOCK,PAYMENT_TYPE,SESSION_START_DT,SESSION_END_DT,METER_EVENT_TYPE,GROSS_PAID_AMT
0,168602671_4_01022019001933,440-05850,GEARY ST 500,CASH,2019/01/02 12:19:33 AM,2019/01/02 12:19:33 AM,NS,0.10
1,168602672_4_01022019002012,440-05170,GEARY ST 500,CASH,2019/01/02 12:20:12 AM,2019/01/02 12:20:12 AM,NS,0.10
2,168602673_4_01022019002623,571-09070,MONTGOMERY ST 900,CASH,2019/01/02 12:26:23 AM,2019/01/02 12:26:23 AM,NS,0.25
3,168602675_4_01022019002626,571-09070,MONTGOMERY ST 900,CASH,2019/01/02 12:26:26 AM,2019/01/02 12:26:26 AM,NS,0.25
4,168602674_4_01022019002632,571-09070,MONTGOMERY ST 900,CASH,2019/01/02 12:26:32 AM,2019/01/02 12:26:32 AM,NS,0.25
...,...,...,...,...,...,...,...,...
27049702,190785279_4_12312019231704,830-06250,EMBARCADERO NORTH 600,CASH,2019/12/31 11:17:04 PM,2019/12/31 11:17:04 PM,NS,0.50
27049703,190785283_4_12312019232704,440-51280,GEARY BLVD 5100,CASH,2019/12/31 11:27:04 PM,2019/12/31 11:27:04 PM,NS,0.25
27049704,190786327_4_12312019233721,324-00230,BATTERY ST 0,CASH,2019/12/31 11:37:21 PM,2019/12/31 11:37:21 PM,NS,1.00
27049705,190785284_4_12312019235457,847-01510,JEFFERSON ST 100,CASH,2019/12/31 11:54:57 PM,2019/12/31 11:54:57 PM,NS,0.50
27049706,190786366_4_12312019235955,666-06250,SUTTER ST 600,CASH,2019/12/31 11:59:55 PM,2019/12/31 11:59:55 PM,NS,0.45

In [21]:
park19['SESSION_START_DT'] = pd.to_datetime(park19['SESSION_START_DT'])
park19['SESSION_END_DT'] = pd.to_datetime(park19['SESSION_END_DT'])

In [62]:
park19['SESSION_HR_DIFF'] = (park19['SESSION_END_DT'] - park19['SESSION_START_DT']) / pd.Timedelta('1 hour')
park19['SESSION_HR_DIFF'].statistics

pd.to_datetime(df['date'],format=date_string_format) 
#park19['SESSION_HR_DIFF'] = park19.apply(lambda row: timedelta.Timedelta(row['SESSION_END_DT'] - row['SESSION_START_DT']), axis=1)

AttributeError: 'Series' object has no attribute 'statistics'

In [65]:
bins = [0, 7, 9, 12, 15, 18, 21, 24]
labels = [
    'midnight to {}'.format(bins[1]),    # 12 - 7?
    '{} to {}'.format(bins[1], bins[2]), # 7 - 9
    '{} to {}'.format(bins[2], bins[3]), # 9 - 12
    '{} to {}'.format(bins[3], bins[4]), # 12 - 3
    '{} to {}'.format(bins[5], bins[6]), # 3 - 6
    '{} to {}'.format(bins[6], bins[7]), # 6 - 9
    '{} to {}'.format(bins[6], bins[7])  # 9 - midnight
    ]

park19['SESSION_START_BIN'] = pd.cut(
    park19['SESSION_START_DT'].dt.hour, bins, labels=labels, 
    right=False, include_lowest=True
    )

count    2.704971e+07
mean     1.059039e+00
std      1.464797e+00
min     -2.303333e+01
25%      2.986111e-01
50%      6.250000e-01
75%      1.433056e+00
max      1.093050e+03
Name: SESSION_HR_DIFF, dtype: float64